### ISSUE TITLE
Higher-order function written as "higher-class"

### ISSUE THREAD

**Issue by federicofrasca796** [ir3ne/javascript-questions-and-answers#1]
### URL
[https://github.com/ir3ne/javascript-questions-and-answers?tab=readme-ov-file#are-concepts-of-higher-class-function-and-closure-connected?](https://github.com/ir3ne/javascript-questions-and-answers?tab=readme-ov-file#are-concepts-of-higher-class-function-and-closure-connected?)

### What specific section or headline is this issue about?
Question n.13 title

### What information was incorrect, unhelpful, or incomplete?
Reading through the questions I found what seems to be a typo in the question n.13 title: 

> 13. Are concepts of higher-class function and closure connected?

### What did you expect to see?

_13. Are concepts of higher-order function and closure connected?_

### Do you have any supporting links, references, or citations?
[https://en.wikipedia.org/wiki/Higher-order_function](https://en.wikipedia.org/wiki/Higher-order_function)

### Do you have anything more you want to share?
Hi @ir3ne!

I just wanted to thank you for the in-depth explanations, I'm finding them useful to prepare myself for an incoming technical interview.

**Comment by ir3ne** [comment]
@federicofrasca796 thanks for reporting the issue. I'm glad this repo is useful for you:)

Issue fixed.
