### ISSUE TITLE
What are Concurrency and Parallelism?

### ISSUE THREAD

**Issue by ir3ne** [ir3ne/javascript-questions-and-answers#15]

**Comment by TBalo** [comment]
> ### Concurrency and Parallelism in JavaScript
>
> In JavaScript, **concurrency** and **parallelism** both enable handling multiple tasks but have different approaches.

---

### 1. Concurrency

Concurrency allows tasks to *appear* to run simultaneously, but they're actually taking turns on a single processor. JavaScript, being single-threaded, handles concurrency using its **event loop** and **asynchronous functions**.

> **Example: Handling Tasks Concurrently**

```javascript
function asyncTask1() {
  return new Promise((resolve) => setTimeout(() => resolve("Task 1 done"), 1000));
}

function asyncTask2() {
  return new Promise((resolve) => setTimeout(() => resolve("Task 2 done"), 500));
}

async function handleTasksConcurrently() {
  const task1 = asyncTask1();
  const task2 = asyncTask2();

  const results = await Promise.all([task1, task2]);
  console.log(results); // Both tasks completed
}

handleTasksConcurrently();


> ### Parallelism in JavaScript
>
> **Parallelism** enables tasks to execute simultaneously on multiple processors or cores, allowing truly concurrent operations. While JavaScript’s runtime is single-threaded, **Web Workers** (in the browser) and **Worker Threads** (in Node.js) allow JavaScript to achieve parallel execution for computationally heavy tasks.

---

### Example: Running Tasks in Parallel with a Web Worker

Web Workers allow the browser to handle intensive tasks on separate threads, preventing them from blocking the main thread.

> **Code Setup:**

1. **Create a Web Worker** in a separate file, e.g., `worker.js`, for heavy computation.
2. **Main Script** communicates with the worker to offload tasks.

```javascript
// worker.js
onmessage = function(e) {
  const result = heavyComputation(e.data); // Perform a heavy computation
  postMessage(result); // Send the result back to the main thread
};

// Main script
const worker = new Worker('worker.js');
worker.postMessage(dataForComputation); // Send data to worker

worker.onmessage = function(e) {
  console.log("Result from worker:", e.data); // Output the worker's result
};

**Comment by TBalo** [comment]
# Parallelism in JavaScript

While JavaScript's default execution model is single-threaded, parallelism can be introduced by using **Web Workers**. Here’s how it works:

## 1. Web Workers

**Overview**: Web Workers allow you to run scripts in background threads. They can perform computations without interfering with the user interface or the main thread, enabling parallel execution of tasks.

**How It Works**: You create a worker using the `Worker` constructor, and the worker runs in its own context. Communication between the main thread and the worker happens through message passing.

### Example: Using Web Workers for Parallelism

**Main Script (main.js)**:
```javascript
// Create a new worker
const worker = new Worker('worker.js');

// Handle messages received from the worker
worker.onmessage = function(event) {
    console.log('Result from worker:', event.data);
};

// Start the worker with an initial message
worker.postMessage('Start computation');

**Comment by ir3ne** [comment]
great @TBalo! do you mind to open a PR for this?
